fix multiple node half rotation MPI error (#324)
Fix the MPI error when running with multiple nodes and performing
`half_rotate`, which involves the following code. `scomm` needs to be
passed into this code.


https://github.com/JoonhoLee-Group/ipie/blob/4b60ce0c923b90e8492b35ffb0e12600d1476ff4/ipie/utils/mpi.py#L117

Otherwise leads to
```
win = MPI.Win.Allocate_shared(nbytes, itemsize, comm=comm)
File "mpi4py/MPI/Win.pyx", line 116, in mpi4py.MPI.Win.Allocate_shared
mpi4py.MPI.Exception: MPI_ERR_RMA_SHARED: Memory cannot be shared
```

@Jinghong-Zhang also met this before.

---------

Co-authored-by: Joonho Lee <linusjoonho@gmail.com>